#!/bin/bash
# Vera Command Center - All commands in one place

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║  🌟 VERA AI COMMAND CENTER                                          ║"
echo "║  Quick Reference for All Operations                                  ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 AGENT MANAGEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start all agents:        ./launch-v2-agents.sh"
echo "Stop all agents:         ./agents/stop-agents.sh"
echo "Check health:            node health-check.mjs"
echo "Live dashboard:          ./dashboard.sh"
echo "View logs:               tail -f ./logs/*.log"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 DEMOS & TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Phase 3 (Sub-agents):   node demo-phase3.mjs"
echo "Phase 4 (Analytics):    node demo-phase4.mjs"
echo "Consensus demo:         node demo-consensus.mjs"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 HASHSCAN TOPICS (Verify on Mainnet)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CORE:    https://hashscan.io/mainnet/topic/0.0.10409351"
echo "DEFI:    https://hashscan.io/mainnet/topic/0.0.10412577"
echo "ENERGY:  https://hashscan.io/mainnet/topic/0.0.10412579"
echo "BRIDGE:  https://hashscan.io/mainnet/topic/0.0.10412578"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 KEY FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Agents:        ./agents/vera-*-v2.mjs"
echo "Blueprints:    ./blueprints/*.mjs"
echo "Logs:          ./logs/*.log"
echo "Reports:       ./gains-report.mjs"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 UTILITY COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Count cycles:     grep -c 'CYCLE #' ./logs/energy-auditor.log"
echo "Check errors:     grep -c '❌\\|Error' ./logs/*.log"
echo "View PID:         cat ./logs/*.pid"
echo "Clear logs:       rm ./logs/*.log"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 BLUEPRINT IMPORTS (for scripts)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "import { VeraAgent } from './blueprints/agent-base.mjs';"
echo "import { coordinator } from './blueprints/coordinator.mjs';"
echo "import { DomainAnalytics } from './blueprints/predictive-analytics.mjs';"
echo "import { TrendCorrelation } from './blueprints/trend-correlation.mjs';"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
