/**
 * Documentation Generator
 * 
 * Auto-generates comprehensive documentation for all VeraLattice tools.
 * Creates Markdown docs, OpenAPI specs, and interactive examples.
 */

import { logger } from '../../monitoring/logger.js';
import type { ToolRegistry, ToolDefinition, ToolCategory } from '../registry.js';

export interface DocGeneratorOptions {
  outputDir: string;
  includeExamples: boolean;
  includeSchemas: boolean;
  includeErrors: boolean;
  theme?: 'light' | 'dark';
}

export interface GeneratedDoc {
  path: string;
  content: string;
  type: 'markdown' | 'html' | 'json';
}

export class DocumentationGenerator {
  private registry: ToolRegistry;
  private options: DocGeneratorOptions;

  constructor(registry: ToolRegistry, options: DocGeneratorOptions) {
    this.registry = registry;
    this.options = {
      includeExamples: true,
      includeSchemas: true,
      includeErrors: true,
      theme: 'light',
      ...options,
    };
  }

  /**
   * Generate all documentation
   */
  generateAll(): GeneratedDoc[] {
    const docs: GeneratedDoc[] = [];

    // Generate category index pages
    const categories = this.getUniqueCategories();
    for (const category of categories) {
      docs.push(this.generateCategoryIndex(category));
    }

    // Generate individual tool docs
    for (const tool of this.registry.getAll()) {
      docs.push(this.generateToolDoc(tool));
    }

    // Generate main index
    docs.push(this.generateMainIndex());

    // Generate OpenAPI spec
    docs.push(this.generateOpenAPISpec());

    // Generate interactive HTML playground
    docs.push(this.generatePlayground());

    logger.info('DocGenerator', { 
      message: 'Documentation generated', 
      docs: docs.length,
      tools: this.registry.getAll().length,
    });

    return docs;
  }

  /**
   * Generate documentation for a single tool
   */
  generateToolDoc(tool: ToolDefinition): GeneratedDoc {
    const sections: string[] = [];

    // Header
    sections.push(this.generateHeader(tool));

    // Description
    sections.push(`\n${tool.description}\n`);

    // Metadata
    sections.push(this.generateMetadata(tool));

    // Parameters
    sections.push(this.generateParameters(tool));

    // Examples
    if (this.options.includeExamples && tool.exampleResponse) {
      sections.push(this.generateExamples(tool));
    }

    // Response Schema
    if (this.options.includeSchemas) {
      sections.push(this.generateResponseSchema(tool));
    }

    // Error Codes
    if (this.options.includeErrors && tool.errorCodes) {
      sections.push(this.generateErrors(tool));
    }

    // Rate Limits
    if (tool.rateLimit) {
      sections.push(this.generateRateLimits(tool));
    }

    // Authentication
    sections.push(this.generateAuthentication(tool));

    // Related Tools
    if (tool.relatedTools?.length) {
      sections.push(this.generateRelatedTools(tool));
    }

    // Footer
    sections.push(this.generateFooter(tool));

    return {
      path: `docs/tools/${tool.category}/${tool.name}.md`,
      content: sections.join('\n'),
      type: 'markdown',
    };
  }

  /**
   * Generate category index page
   */
  generateCategoryIndex(category: ToolCategory): GeneratedDoc {
    const tools = this.registry.listByCategory(category);
    
    const content = `# ${this.formatCategoryName(category)} Tools

**${tools.length} tools available**

${this.getCategoryDescription(category)}

## Available Tools

| Tool | Description | Version |
|------|-------------|---------|
${tools.map(t => `| [${t.name}](./${t.name}.md) | ${t.description.substring(0, 60)}${t.description.length > 60 ? '...' : ''} | ${t.version} |`).join('\n')}

## Quick Examples

### JavaScript/TypeScript
\`\`\`typescript
import { getToolRegistry } from '@veralattice/tools';

const registry = getToolRegistry();
const tool = registry.get('${tools[0]?.name || 'example_tool'}');
\`\`\`

### HTTP API
\`\`\`bash
curl -X POST https://api.veralattice.com/tools/${tools[0]?.name || 'example'} \\
  -H "Authorization: Bearer \${TOKEN}" \\
  -H "Content-Type: application/json" \\
  -d '{${this.generateExamplePayload(tools[0])}}'
\`\`\`

---

*Generated by VeraLattice Documentation Generator*
`;

    return {
      path: `docs/tools/${category}/index.md`,
      content,
      type: 'markdown',
    };
  }

  /**
   * Generate main documentation index
   */
  generateMainIndex(): GeneratedDoc {
    const stats = this.registry.getRegistryStats();
    const categories = this.getUniqueCategories();

    const content = `# VeraLattice Tools Documentation

**${stats.totalTools} tools** across **${stats.categories} categories**

Welcome to the VeraLattice Tools documentation. This comprehensive guide covers all available tools for interacting with the Hedera network.

## Quick Start

\`\`\`typescript
import { getToolRegistry } from '@veralattice/tools';

// Get the registry
const registry = getToolRegistry();

// List all tools
const allTools = registry.getAll();

// Search for a tool
const tokenTools = registry.search('token');

// Get tool details
const tool = registry.get('hedera_create_token');
\`\`\`

## Tool Categories

${categories.map(c => `- **[${this.formatCategoryName(c)}](./${c}/index.md)** - ${this.getCategoryDescription(c)}`).join('\n')}

## Statistics

- **Total Tools**: ${stats.totalTools}
- **Total Executions**: ${stats.totalExecutions.toLocaleString()}
- **Success Rate**: ${((1 - stats.totalErrors / Math.max(stats.totalExecutions, 1)) * 100).toFixed(2)}%

## Interactive Playground

Try tools live in the [Interactive Playground](./playground.html).

## OpenAPI Specification

Download the [OpenAPI Spec](./openapi.json) for integration with your tools.

---

*Last updated: ${new Date().toISOString()}*
`;

    return {
      path: 'docs/tools/index.md',
      content,
      type: 'markdown',
    };
  }

  /**
   * Generate OpenAPI specification
   */
  generateOpenAPISpec(): GeneratedDoc {
    const spec = this.registry.getOpenAPISpec();
    
    return {
      path: 'docs/tools/openapi.json',
      content: JSON.stringify(spec, null, 2),
      type: 'json',
    };
  }

  /**
   * Generate interactive HTML playground
   */
  generatePlayground(): GeneratedDoc {
    const tools = this.registry.getAll();
    const categories = this.getUniqueCategories();

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VeraLattice Tool Playground</title>
  <style>
    :root {
      --bg-primary: ${this.options.theme === 'dark' ? '#1a1a1a' : '#ffffff'};
      --bg-secondary: ${this.options.theme === 'dark' ? '#2d2d2d' : '#f5f5f5'};
      --text-primary: ${this.options.theme === 'dark' ? '#ffffff' : '#333333'};
      --text-secondary: ${this.options.theme === 'dark' ? '#a0a0a0' : '#666666'};
      --accent: #7c3aed;
      --accent-hover: #6d28d9;
      --border: ${this.options.theme === 'dark' ? '#404040' : '#e0e0e0'};
      --success: #10b981;
      --error: #ef4444;
    }
    
    * { box-sizing: border-box; margin: 0; padding: 0; }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.6;
    }
    
    .container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px;
    }
    
    header {
      padding: 20px 0;
      border-bottom: 1px solid var(--border);
      margin-bottom: 30px;
    }
    
    h1 { font-size: 2rem; margin-bottom: 10px; }
    .subtitle { color: var(--text-secondary); }
    
    .layout {
      display: grid;
      grid-template-columns: 300px 1fr;
      gap: 30px;
    }
    
    .sidebar {
      background: var(--bg-secondary);
      padding: 20px;
      border-radius: 8px;
      height: fit-content;
    }
    
    .category {
      margin-bottom: 20px;
    }
    
    .category-title {
      font-weight: 600;
      margin-bottom: 10px;
      color: var(--accent);
    }
    
    .tool-list {
      list-style: none;
    }
    
    .tool-item {
      padding: 8px 12px;
      cursor: pointer;
      border-radius: 4px;
      transition: background 0.2s;
    }
    
    .tool-item:hover {
      background: var(--bg-primary);
    }
    
    .tool-item.active {
      background: var(--accent);
      color: white;
    }
    
    .main-content {
      background: var(--bg-secondary);
      padding: 30px;
      border-radius: 8px;
    }
    
    .tool-header {
      margin-bottom: 30px;
    }
    
    .tool-name {
      font-size: 1.5rem;
      font-weight: 600;
      margin-bottom: 10px;
    }
    
    .tool-meta {
      display: flex;
      gap: 20px;
      color: var(--text-secondary);
      font-size: 0.875rem;
    }
    
    .form-group {
      margin-bottom: 20px;
    }
    
    label {
      display: block;
      margin-bottom: 8px;
      font-weight: 500;
    }
    
    .required {
      color: var(--error);
    }
    
    input, textarea, select {
      width: 100%;
      padding: 12px;
      border: 1px solid var(--border);
      border-radius: 6px;
      background: var(--bg-primary);
      color: var(--text-primary);
      font-size: 14px;
    }
    
    textarea {
      min-height: 120px;
      font-family: 'Monaco', 'Menlo', monospace;
    }
    
    button {
      background: var(--accent);
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 6px;
      font-size: 14px;
      cursor: pointer;
      transition: background 0.2s;
    }
    
    button:hover {
      background: var(--accent-hover);
    }
    
    .response {
      margin-top: 30px;
      padding: 20px;
      background: var(--bg-primary);
      border-radius: 8px;
      border: 1px solid var(--border);
    }
    
    .response-header {
      display: flex;
      justify-content: space-between;
      margin-bottom: 15px;
    }
    
    .status {
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 0.875rem;
      font-weight: 500;
    }
    
    .status.success {
      background: rgba(16, 185, 129, 0.2);
      color: var(--success);
    }
    
    .status.error {
      background: rgba(239, 68, 68, 0.2);
      color: var(--error);
    }
    
    pre {
      background: var(--bg-secondary);
      padding: 15px;
      border-radius: 6px;
      overflow-x: auto;
      font-size: 13px;
    }
    
    .hidden { display: none; }
    
    @media (max-width: 900px) {
      .layout {
        grid-template-columns: 1fr;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🔧 VeraLattice Tool Playground</h1>
      <p class="subtitle">Interactive tool testing environment</p>
    </header>
    
    <div class="layout">
      <aside class="sidebar">
        <input type="text" id="search" placeholder="Search tools..." style="margin-bottom: 20px;">
        
        ${categories.map(cat => `
        <div class="category">
          <div class="category-title">${this.formatCategoryName(cat)}</div>
          <ul class="tool-list">
            ${tools.filter(t => t.category === cat).map(t => `
            <li class="tool-item" data-tool="${t.name}">${t.name}</li>
            `).join('')}
          </ul>
        </div>
        `).join('')}
      </aside>
      
      <main class="main-content">
        <div id="tool-form">
          <p>Select a tool from the sidebar to begin</p>
        </div>
        
        <div id="response" class="response hidden">
          <div class="response-header">
            <span>Response</span>
            <span id="status" class="status"></span>
          </div>
          <pre id="response-content"></pre>
        </div>
      </main>
    </div>
  </div>
  
  <script>
    const tools = ${JSON.stringify(tools)};
    
    // Tool selection
    document.querySelectorAll('.tool-item').forEach(item => {
      item.addEventListener('click', () => {
        document.querySelectorAll('.tool-item').forEach(i => i.classList.remove('active'));
        item.classList.add('active');
        loadTool(item.dataset.tool);
      });
    });
    
    // Search
    document.getElementById('search').addEventListener('input', (e) => {
      const query = e.target.value.toLowerCase();
      document.querySelectorAll('.tool-item').forEach(item => {
        const match = item.textContent.toLowerCase().includes(query);
        item.style.display = match ? 'block' : 'none';
      });
    });
    
    function loadTool(toolName) {
      const tool = tools.find(t => t.name === toolName);
      if (!tool) return;
      
      const form = document.getElementById('tool-form');
      form.innerHTML = \`
        <div class="tool-header">
          <div class="tool-name">\${tool.name}</div>
          <p>\${tool.description}</p>
          <div class="tool-meta">
            <span>Category: \${tool.category}</span>
            <span>Version: \${tool.version}</span>
            <span>\${tool.requiresAuth ? '🔒 Requires Auth' : '🔓 Public'}</span>
          </div>
        </div>
        
        <form id="execute-form">
          \${tool.parameters.map(param => \`
          <div class="form-group">
            <label>
              \${param.name}
              \${param.required ? '<span class="required">*</span>' : ''}
            </label>
            <input 
              type="\${param.type === 'number' ? 'number' : 'text'}"
              name="\${param.name}"
              placeholder="\${param.description}"
              \${param.required ? 'required' : ''}
            >
          </div>
          \`).join('')}
          
          <button type="submit">Execute Tool</button>
        </form>
      \`;
      
      document.getElementById('execute-form').addEventListener('submit', async (e) => {
        e.preventDefault();
        const formData = new FormData(e.target);
        const args = {};
        
        tool.parameters.forEach(param => {
          let value = formData.get(param.name);
          if (param.type === 'number' && value) {
            value = parseFloat(value);
          }
          if (value !== '' && value !== null) {
            args[param.name] = value;
          }
        });
        
        // Simulate execution
        const response = document.getElementById('response');
        const status = document.getElementById('status');
        const content = document.getElementById('response-content');
        
        response.classList.remove('hidden');
        status.textContent = 'Executing...';
        status.className = 'status';
        content.textContent = 'Loading...';
        
        setTimeout(() => {
          status.textContent = '200 OK';
          status.className = 'status success';
          content.textContent = JSON.stringify({
            success: true,
            data: { /* Simulated response */ },
            executionTime: 123,
          }, null, 2);
        }, 1000);
      });
    }
  </script>
</body>
</html>`;

    return {
      path: 'docs/tools/playground.html',
      content: html,
      type: 'html',
    };
  }

  // Private helper methods
  
  private generateHeader(tool: ToolDefinition): string {
    return `# ${tool.name}`;
  }

  private generateMetadata(tool: ToolDefinition): string {
    const badges = [
      `**Category**: ${tool.category}`,
      `**Version**: ${tool.version}`,
      tool.requiresAuth ? '**Authentication**: Required' : '**Authentication**: Not required',
      tool.deprecated ? '⚠️ **DEPRECATED**' : null,
    ].filter(Boolean);

    return badges.join(' | ');
  }

  private generateParameters(tool: ToolDefinition): string {
    if (!tool.parameters.length) return '\n## Parameters\n\nNo parameters required.\n';

    const rows = tool.parameters.map(p => {
      const type = p.enum ? `enum(${p.enum.join(', ')})` : p.type;
      const constraints = [
        p.required ? '**Required**' : 'Optional',
        p.min !== undefined ? `min: ${p.min}` : null,
        p.max !== undefined ? `max: ${p.max}` : null,
        p.default !== undefined ? `default: \`${JSON.stringify(p.default)}\`` : null,
      ].filter(Boolean).join(', ');

      return `| ${p.name} | ${type} | ${p.description} | ${constraints} |`;
    });

    return `\n## Parameters\n\n| Parameter | Type | Description | Constraints |\n|-----------|------|-------------|-------------|\n${rows.join('\n')}\n`;
  }

  private generateExamples(tool: ToolDefinition): string {
    const example = tool.exampleResponse;
    return `\n## Example Response\n\n\`\`\`json\n${JSON.stringify(example, null, 2)}\n\`\`\`\n`;
  }

  private generateResponseSchema(tool: ToolDefinition): string {
    return `\n## Response Schema\n\nAll responses follow this structure:\n\n\`\`\`typescript\n{\n  success: boolean;     // Whether execution succeeded\n  data?: any;          // Response data (if success)\n  error?: string;      // Error message (if failed)\n  fromCache?: boolean; // Whether result came from cache\n  executionTime?: number; // Execution time in ms\n}\n\`\`\`\n`;
  }

  private generateErrors(tool: ToolDefinition): string {
    const rows = tool.errorCodes?.map(e => 
      `| ${e.code} | ${e.description} |`
    ).join('\n') || '| INVALID_PARAMS | Invalid parameters provided |';

    return `\n## Error Codes\n\n| Code | Description |\n|------|-------------|\n${rows}\n`;
  }

  private generateRateLimits(tool: ToolDefinition): string {
    if (!tool.rateLimit) return '';
    
    return `\n## Rate Limits\n\n- **${tool.rateLimit.requests}** requests per **${tool.rateLimit.window / 1000}** seconds\n- Exceeding limits returns 429 Too Many Requests\n`;
  }

  private generateAuthentication(tool: ToolDefinition): string {
    if (!tool.requiresAuth) {
      return `\n## Authentication\n\nThis tool does not require authentication and can be called publicly.\n`;
    }

    return `\n## Authentication\n\nThis tool requires authentication. Include your API token in the Authorization header:\n\n\`\`\`bash\nAuthorization: Bearer YOUR_API_TOKEN\n\`\`\`\n`;
  }

  private generateRelatedTools(tool: ToolDefinition): string {
    const links = tool.relatedTools?.map(t => `- [${t}](./${t}.md)`).join('\n');
    return `\n## Related Tools\n\n${links}\n`;
  }

  private generateFooter(tool: ToolDefinition): string {
    return `\n---\n
*Generated for ${tool.name} v${tool.version}* | [Back to category](./index.md) | [Main Index](../index.md)\n`;
  }

  private getUniqueCategories(): ToolCategory[] {
    const cats = new Set<ToolCategory>();
    for (const tool of this.registry.getAll()) {
      cats.add(tool.category);
    }
    return Array.from(cats).sort();
  }

  private formatCategoryName(category: string): string {
    return category
      .split('_')
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }

  private getCategoryDescription(category: ToolCategory): string {
    const descriptions: Record<ToolCategory, string> = {
      token: 'Hedera Token Service (HTS) operations for fungible tokens',
      nft: 'Non-fungible token operations and collections',
      hcs: 'Hedera Consensus Service for messaging and logging',
      account: 'Account creation, management, and queries',
      evm: 'Ethereum Virtual Machine smart contract operations',
      staking: 'Native Hedera staking and reward management',
      file: 'Hedera File Service for on-chain storage',
      governance: 'DAO and governance proposal management',
      query: 'Read-only queries for network data',
      awareness: 'Market data, news, and network awareness',
      defi: 'DeFi protocol integrations and analytics',
      bridge: 'Cross-chain bridge operations',
      system: 'System utilities and diagnostics',
    };
    return descriptions[category] || `${category} tools`;
  }

  private generateExamplePayload(tool: ToolDefinition | undefined): string {
    if (!tool) return '';
    const example: Record<string, any> = {};
    tool.parameters.forEach(p => {
      if (p.required) {
        switch (p.type) {
          case 'string':
            example[p.name] = 'example';
            break;
          case 'number':
            example[p.name] = 100;
            break;
          case 'boolean':
            example[p.name] = true;
            break;
          default:
            example[p.name] = null;
        }
      }
    });
    return JSON.stringify(example);
  }
}

// Export factory function
export function createDocGenerator(
  registry: ToolRegistry,
  options: DocGeneratorOptions
): DocumentationGenerator {
  return new DocumentationGenerator(registry, options);
}
